apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-page
data:
  index.html: |
    <html>
      <body style="font-family:sans-serif;text-align:center;margin-top:50px;">
        <h1>Hello from Argo CD + GitHub + EKS 🚀</h1>
        <p>This page is served by NGINX running in Kubernetes.</p>
      </body>
    </html>
